custom: ["https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7LZEP85BLPTQG&source=url", PayPal]
custom: ["https://www.paypal.me/JoshTurgasen", PayPal.me]
custom: ["https://www.amazon.com/hz/wishlist/ls/3HMKLRHLLV6FG?ref_=wl_share", Amazon Wishlist]
